### ISSUE TITLE
missing in action: Common Helper for development 

### ISSUE THREAD

**Issue by Aliazzzz** [stefandreyer/CODESYS-MQTT#1]
The Common Helper for development Library (CommonTypesAndFunctions) is not provided, so the project cannot compile succesfully.
Maybe a .Projectarchive would be more fitting? i.e. all dependancies (libs etc) can be attached.

**Comment by Aliazzzz** [comment]
Found it!

**Comment by stefandreyer** [comment]
Hello Aliazzz,

yes i split this 2 things. so development of TLS an MQTT can be done from diffrent teams. 
This is cause of non git support of CODESYS(and not subversion for 500€)


BR Stefan
