### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by sokura23** [stefandreyer/CODESYS-MQTT#10]
Hi! Can i use this library in Codesys v3.5 SP11 Patch 5? Can you send me example for my codesys version? Thanks!

**Comment by stefandreyer** [comment]
Hi,

I'll have a look and try it.


Br stefan

**Comment by sokura23** [comment]
Thank you very much. Let me know when you'll do it. OK?

**Comment by stefandreyer** [comment]
Hi,

I made a ZIP file with 3.5 sp 11. Please test it.


BR Stefan
