### ISSUE TITLE
use username and password

### ISSUE THREAD

**Issue by zhapwey** [stefandreyer/CODESYS-MQTT#11]
Hello:
First of all congratulations for the work
I have tested your library for mqtt and it works very well. I tried to mount some tests in cloudMQTT that requires username and password and I have not managed to publish or subscribe to any topic.
Could you tell me how to do it?

**Comment by stefandreyer** [comment]
Hello Zzhapwey,

i have to admit that i implemented username and password, but never tested it...
so first look if the tls Connection is established. So have a look into the Ethernet by wireshart, or look into MQTT_CONTROLL if step is at least 30 TLS Connection is done.

BR Stefan

**Comment by BMBIT-oss** [comment]
Hi Stefan , 
How can we set the user and the password ?
I can see it in the COM .
![STEFAN MQTT USER PASS](https://user-images.githubusercontent.com/34801911/55375208-c15d4200-54e1-11e9-8711-6ab42a1f6409.jpg)

**Comment by stefandreyer** [comment]
Hi Silviu,

i need to correct here something ....

BR Stefan

**Comment by stefandreyer** [comment]
Hi Silviu,

solved. Please use this for username and password in HANDLE_MQTT:
	`//use format: user:password@domain:port`
	`URL : STRING(OSCAT_BASIC.STRING_LENGTH);`

BR Stefan

**Comment by BMBIT-oss** [comment]
Hi Stefan , 
Thanks for looking in to this .
You have made already an amazing job by creating this MQTT FB .
I will give it a try tonight and report back .
