### ISSUE TITLE
No memory Error when trying notls on wago pfc100

### ISSUE THREAD

**Issue by sanderobdeijn** [stefandreyer/CODESYS-MQTT#18]
Has anyone tested this on the wago pfc 100?
It tried to execute TestOutOfTheBoxNoTLS and on build it says.
C0265:  No memory for dynamic object creation defined for application 'Device.Application'

Does anyone know what this means and how to fix it?

**Comment by stefandreyer** [comment]
Hi Sander,

Right click on application propertis there somewehre you can set the dynamic memory.

My projekt uses dynamic allocated memory, but you have to activate it.

Did you use the Projekt or the FB?

BR Stefan

**Comment by sanderobdeijn** [comment]
Thank you that was the problem.

**Comment by sanderobdeijn** [comment]
btw Stefan what do you mean with Projekt or the FB.
What is a FB exactly
And how can I see if the message is sent to test.mosquitto.org. 
I'm connected to the broker but I don't recognize a message.

**Comment by stefandreyer** [comment]
Hi Sander,

Project i mean the test Projects you can find in my repository. FB are the POUs which called in the projects.
FB --> German: Funktionsbaustein. englich fucntionblock???

BR Stefan

**Comment by stefandreyer** [comment]
Hi,

please test if test.mosquitto.org is online...

often it is not ...

then use somthing like mqtt fx to check the messages on the broker.

In MQTT_IN_OUT you'll se if the client is connected to the broker.

there is a var BROKER_CONNECTED if true, client is connected.

BR Stefan
