### ISSUE TITLE
Receive typo

### ISSUE THREAD

**Issue by sanderobdeijn** [stefandreyer/CODESYS-MQTT#20]
In multiple places receive and received are written as recive and recived.
Not a big problem, but something that I noticed 😟.

**Comment by stefandreyer** [comment]
Hi Sander,
I'll check and correct this.
Thanks for the tip.
BR Stefan

**Comment by stefandreyer** [comment]
Hi Sander,

done the typos. You'll see in the next release.

BR Stefan

**Comment by sanderobdeijn** [comment]
great thanks

**Comment by stefandreyer** [comment]
Hi,

done…

BR Stefan
