### ISSUE TITLE
Codesys MQTT Add Library Problem

### ISSUE THREAD

**Issue by wildanfathur** [stefandreyer/CODESYS-MQTT#26]
Hello Stefan,
I am interested in using MQTT on codesys using the library that you created. However, when I try to add the library, an error like this appears:

![image](https://user-images.githubusercontent.com/24538344/66530748-48474300-eb33-11e9-86c8-a851491d88af.png)

what should I do?

**Comment by stefandreyer** [comment]
Hi, 

please Download the latest Library 1.1.0.0. Then try the button Download Missing Librarys.

BR Stefan

**Comment by wildanfathur** [comment]
Hi, thanks for the solution, 
there is any basic tutorial on how to use this MQTT library?

Can this MQTT library be used in 32-bit codesys?

**Comment by stefandreyer** [comment]
Hi,

there isn't a tutorial yet. Have a look at the examples, they should help you.

I think 32bit codesys should be fine.

BR Stefan

**Comment by wildanfathur** [comment]
Ok, but I've try open the GreatExampleOfAdvantages.project, but I found the problem like this:
![image](https://user-images.githubusercontent.com/24538344/67831468-0b0e1980-fb11-11e9-8214-e332971ad336.png)
I am using CODESYS V3.5 SP15
is there any suggestion for me ?

**Comment by primsam** [comment]
Yes , you have to Update or Download the Missing device description . Look at the Red Warnung in the left Corner
