### ISSUE TITLE
Installed Codesys-MQTT Library

### ISSUE THREAD

**Issue by fidarin** [stefandreyer/CODESYS-MQTT#28]
Hi Stefan, I am interested in your Codesys-MQTT project. Unfortunately, I found these errors after I have installed all libraries from the project's repository. The version of Codesys is Codesys V3.5 SP 15 Patch 1 (32 bit). Is there any problem with the version I am using?
![Capture1](https://user-images.githubusercontent.com/38461374/68186162-02688800-ffd6-11e9-8c88-c16ebffde775.PNG)
![Capture2](https://user-images.githubusercontent.com/38461374/68186163-03011e80-ffd6-11e9-84dc-bba675c97cbd.PNG)
![Capture3](https://user-images.githubusercontent.com/38461374/68186164-03011e80-ffd6-11e9-9ccd-ddde68d73877.PNG)

**Comment by stefandreyer** [comment]
Hi,
try download missing librarys.
BR Stefan

 
 
  Am Di., Nov. 5, 2019 at 8:11 schrieb fidarin<notifications@github.com>:   
Hi Stefan, I am interested in your Codesys-MQTT project. Unfortunately, I found these errors after I have installed all libraries from the project's repository. The version of Codesys is Codesys V3.5 SP 15 Patch 1 (32 bit). Is there any problem with the version I am using?

**Comment by fidarin** [comment]
I have installed and added the needed libraries in Codesys, but same errors are still appearing. Is there any other software components that I should have renewed?

**Comment by stefandreyer** [comment]
Hi,

there should be a button in you library manager for this purpose, did you try it?

BR Stefan

**Comment by fidarin** [comment]
Hi,

I've clicked the "Download Missing Libraries" button. At first, some missing libraries were detected and installed. The number of errors were being reduced from 34 to 29.

I tried the same thing because unfortunately some libraries are still remain undetected and there were still 29 errors. But there aren't any missing library in "Download Missing Libraries" window just like in this photo. Do you have any suggestion?

![Capture4](https://user-images.githubusercontent.com/38461374/68357658-a3775000-0148-11ea-8597-b1f4959391a6.PNG)

**Comment by stefandreyer** [comment]
Hi @fidarin 

is this one of my GitHub projects? If so you have to change the PLC into the 32bit version. The Projects are made with 64bit PLC.

![grafik](https://user-images.githubusercontent.com/41088808/68360081-e1f81500-011e-11ea-860e-4167737ffdcd.png)


BR Stefan

**Comment by fidarin** [comment]
Yes,
![Capture6](https://user-images.githubusercontent.com/38461374/68365638-d713a380-0163-11ea-9e21-8663751b714a.PNG)

That was wrong of me that I didn't notice the "x64". I sincerely apologize @stefandreyer. I wish I had been more conscious and not going to do it again in the future.

**Comment by fidarin** [comment]
Hi Stevan,

I've already used the 64 bit version of Codesys
![Capture11](https://user-images.githubusercontent.com/38461374/68447226-ccafe300-0211-11ea-8b0f-d829f4af5f56.PNG)

But the project and several libraries still haven't been detected. The aren't any missing library when I opened the "Download Missing Libraries Window". What should I do?
![Capture12](https://user-images.githubusercontent.com/38461374/68447262-e9e4b180-0211-11ea-9c04-4581c567b19d.PNG)

**Comment by stefandreyer** [comment]
hi @fidarin,

I never had fun with both x32 and x64 versions installed. You still have?

You still have both? 

Please try to have just on on your system.

BR Stefan

**Comment by fidarin** [comment]
hi @stefandreyer ,
No, I've uninstalled the x32 version and deleted all the remaining x32 files before I install the x64. But that just happened.

**Comment by stefandreyer** [comment]
Hi @fidarin 

uninstalling the 32bit verion allways work for me. 

Try download missing device description, right click on the PLC.

Or changer the PLC to the PLC of you CODESYS Version. Right click on PLC, update device.

BR Stefan
