### ISSUE TITLE
Split Lampbase in Lampbase and Switchbase

### ISSUE THREAD

**Issue by sanderobdeijn** [stefandreyer/CODESYS-MQTT#29]
I want to write my switching logic in an external system (OpenHab)
Because of that I would like to have a switchbase fb that just publishes to mqtt and maybe a variable for testing and fallback scenarios. But without the statemanagement.
Bonus points for also having different messages for a short and a long press or or adding pressdown time.

And a lampbase that listens to mqtt and maybe a variable for testing and fallback scenarios.
This should probably have statemanagement.

Can I just copy the lampbase and take out the statemanagement and recieving logic?

**Comment by stefandreyer** [comment]
Hi @sanderobdeijn 

yes you can. You are free to build pure receive and transmit FB's

for inspiration of long and short press time have a look to:

[https://github.com/MichielVanwelsenaere/HomeAutomation.CoDeSys3](url)

or the OSCAT librarys

This projekt is using my library.

BR Stefan
