### ISSUE TITLE
20 unresolved references after download (Crypto related)

### ISSUE THREAD

**Issue by MartijnVanAlphen** [stefandreyer/CODESYS-MQTT#31]
Dear Stefan,

Trying to run your MQTT library on an Epec 6200 controller. Codesys 3.5.13 (newer is not recommended for now by Epec).

I managed to get all the libraries installed (downloading missing libraries only helped partially). To compile the application all works fine now (I had to add ^ to DATA.PayloadString and StrPt in ReceiveValue.PublishReceived and had to change CommonTypesAndFunctions.FindLastDot to CommonTypesAndFunctions.FindLasDot until I realized that you have an updated version of the library in a different repository, still version 1.0.0.0 according to Codesys though).

So it compiles with no errors. But after downloading I get 20 errors, all Unresolved references related to Crypto. I did install the CmpCrypto library, version 3.5.11.0. Don't know whether it is actually related to this library. Any idea what this could be? Is there a way to work around this?

Out of curiosity: Yesterday you replaced MQTT.library v1.1.0.0 with a different v1.1.0.0. What changed?

![image](https://user-images.githubusercontent.com/58737237/70540928-60a10180-1b66-11ea-9ea9-56d89e9a8f3f.png)

Thanks, Martijn

**Comment by stefandreyer** [comment]
Hi Martijn,

old Story,

your PLC Manufactor doesn implement openSSL on your plc.
Doesn't they like security in Finnland? ;) Open a case at Epec, Maybe they implement it...

For your solution look here:

[https://github.com/stefandreyer/CODESYS-MQTT/issues/25#issuecomment-544242203](url)

My Change yesterday:

receive publish with renaining lenght of 128 Bytes will crash calculation of remaining length.

I solved this.
And some other minor Things....
BR Stefan

**Comment by MartijnVanAlphen** [comment]
Thanks Stefan! 

I didn't realize this to be the same, since I have no building errors.

I'll give this solution a try and let you know. For sure I'll check with Epec about this!

Martijn

**Comment by MartijnVanAlphen** [comment]
Unfortunately not much changed. Moved to 18 unresolved references now, instead of 20. The library CmpTls is completely not there (does give me an error at first, but will let me download anyway).

Can you point me in the direction where these references are used? I can't find any in the libraries nor in the project.

Martijn

**Comment by stefandreyer** [comment]
Hi Martijn,

just delete CmpTls library out of commonTypesAndFunction, then compile(check pool objects in build) and you will see the usage.

![image](https://user-images.githubusercontent.com/41088808/70742614-3bef8a00-1d1e-11ea-9549-b81bcea8395c.png)

BR Stefan

**Comment by MartijnVanAlphen** [comment]
It is exactly what I did before. Didn't help.

Martijn

**Comment by stefandreyer** [comment]
Hi Martijn,
please try to delete CmpCrypto too…

![image](https://user-images.githubusercontent.com/41088808/71368924-92c05380-25a9-11ea-87e7-a21058e73d1c.png)


BR Stefan

**Comment by stefandreyer** [comment]
And it is in the mqtt lib too.

BR stefan

**Comment by MartijnVanAlphen** [comment]
Thanks Stefan! I'll try it after holidays. Have a nice Christmas!

Martijn

**Comment by stefandreyer** [comment]
Hi Martjin,

did you had luck?

BR Stefan
