### ISSUE TITLE
Support for x64 Devices?

### ISSUE THREAD

**Issue by rdcoulton** [stefandreyer/CODESYS-MQTT#34]
Hi,

I have you done any work to-date to enable the MQTT library to work on 64 PLC devices?

From what I can see its the reliance on SysSocket23 library that is not supported. I have tried to replace it with another that works on 64 PLCs but it just seams to create more errors.

Any thoughts would be appreciated as it worked well on our original system.

Thanks.

**Comment by stefandreyer** [comment]
Hi,

the lib works for both 32 and 64 bits. I develop it under 64 bit with 64 bit windows plc and use it with the raspi...

All Windows examples im my repository are for 64 bit, You may have a look at them.

What is your target plc?

BR Stefan

**Comment by FeLiiix** [comment]
Hi Stefan, 

I have the same issue. My runtime is on a Proxmox LCX container (Linux).

![image](https://github.com/stefandreyer/CODESYS-MQTT/assets/43402751/6e117edb-a329-4a0c-a4ed-bfcf1e8bfdfd)

I use the latest version of the library.

![image](https://github.com/stefandreyer/CODESYS-MQTT/assets/43402751/acd73990-112c-461b-8679-3ecc72c960a0)

**Comment by stefandreyer** [comment]
Hi Felix,
what do you use for a PLC? Still I have no Problems in my 64Bit Test Environment on PC.
What is the exact Error? Didn't see it in your Screenshots.
BR Stefan
    Am Dienstag, 26. Dezember 2023 um 20:32:16 MEZ hat FeLiiix ***@***.***> Folgendes geschrieben:  
 
 


Hi Stefan,

I have the same issue. My runtime is on a Proxmox LCX container (Linux).

image.png (view on web)

I use the latest version of the library.

image.png (view on web)

**Comment by 8OND007** [comment]
same error here on the last version of TwinCAT v3.1.
I too see an error that syssocket23.lib is only supported in 32-bit applications : 

![image](https://github.com/stefandreyer/CODESYS-MQTT/assets/43314247/47f652f7-bb99-4c2d-a08d-6009324bbc2f)

Is there any free open source function block available to use MQTT on Beckhoff TwinCAT 3.1 ? I'd like to use it on a Beckhoff IPC running BSD (x64)
