### ISSUE TITLE
Publish works from Function Block but how do I subscribe?

### ISSUE THREAD

**Issue by jshroyer031** [stefandreyer/CODESYS-MQTT#35]
I was able to successfully publish to an MQTT broker using this function block in Codesys running on a raspberry pi but the function block did not have a subscribe option... can anyone help?

**Comment by stefandreyer** [comment]
Hi,

yes my docu is poor ;)

subscription are done with the subscription FB wich gets the subscription topic and a callback collector. If the client gets a packet for the subscription all receive methods collectet in the collector are called and the FBs can check if the topic fits to them.

Please look to [https://github.com/stefandreyer/CODESYS-zigbee2mqtt](url) too how this makes things easyer.

More questions? Feel free...

BR Stefan

**Comment by jshroyer031** [comment]
Stefan,

Thank you for the response! Great job by the way figuring this all out.
This is wonderful. I cannot open the link that you sent to me
unfortunately. Not sure why.

Thanks,

Jordan

**Comment by stefandreyer** [comment]
hi

try this

https://github.com/stefandreyer/CODESYS-zigbee2mqtt
