### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by ptC7H12** [stefandreyer/CODESYS-MQTT#37]
The compiler throws some errors, please have a look at the picture below.  What can I do?
My PLC ist a Wago PFC200.

![image](https://user-images.githubusercontent.com/4460900/77120448-300c1600-6a39-11ea-9b2a-14b8f7436d18.png)

**Comment by stefandreyer** [comment]
Hi,

geht deutsch?

du musst in deinem Projekteinstellungen den Dynamischen Speicher aktivieren. so 50kB solltne tun.

siehe

https://github.com/stefandreyer/CODESYS-MQTT/issues/18

Grüße Stefan

**Comment by ptC7H12** [comment]
Ich habe es jetzt so weit am laufen, allerdings habe ich noch nicht herausgefunden, wie ich an den Inhalt der Subscribtion komme... Kannst du mir da helfen?
![image](https://user-images.githubusercontent.com/4460900/77238380-b5c1ca00-6bcf-11ea-838e-f35bd27f199e.png)

**Comment by stefandreyer** [comment]
Hi,

der Inhalt der Empfangenen Daten landet in den FB's die du mit dem collector gesammelt hast. bei den FBs wird die Methode PublishReceived aufgerufen, welche die Daten dann Prüfen kann.

Für einen ersten Eindruck der Daten kannst du einen Breakpoint in publishReceived des collectors setzten und dir unter Data die empfangenen daten anschauen.

Grüße

**Comment by ptC7H12** [comment]
Ich bin gerade dabei das mit dem Subscriber zu testen.

Was mir aber gerade auffällt ist:

1. Wenn der Broker nicht erreichbar ist und der Client in den Timeout geht - wie komme ich da wieder raus?

2.  Wenn ich dann z.B. die Adresse des Brokers wechsle, geht der trotzdem nicht in den connected status über, weil er im MQTT_Client zwischen Schritt 10 und 60 wechselt (fehlender Dynamische Speicher). Ich muss dann erst händisch den Schritt auf 0 setzen und den Speicher erhöhen. Dann erst baut er die Verbindung neu auf.
(Der markierte Schritt wechselte zwischen 10 und 60)
![image](https://user-images.githubusercontent.com/4460900/77258918-14de1800-6c7e-11ea-9279-f343e3086590.png)

**Comment by ptC7H12** [comment]
Habe das hinbekommen, war etwas schwer das Konzept dahinter zu verstehen, aber Respekt, wenn man es mal verstanden hat, ist es echt gut!

_________
Update:
Immer wieder das Problem mit den springen zwischen Schritt 0 und 60, obwohl ich den Speicher schon auf 100k erhöht habe.
![image](https://user-images.githubusercontent.com/4460900/77424750-ec673280-6dd1-11ea-9116-5ba55d77c88a.png)
Nach manuellen setzen auf Schritt 0 geht der wieder in Schritt 40:

Krieg es nicht mehr zum laufen. Auch nicht nach Erhöhung des Speichers.
Haltepunkt auf PublishReceived wird nie ausgeführt.
![image](https://user-images.githubusercontent.com/4460900/77425833-a317e280-6dd3-11ea-9184-b61bead458dd.png)

Habe auch schon mal Manuell des destroy ausgeführt, hat auch nichts gebracht. 
Im MQTT_Handle werden wenn ich was schicke auch die COM.R_BUF Bytes nicht hochgezählt
Das connected Bit ist true

Auch das Publish geht nicht mehr, ging vorhin auch schon.

**Comment by stefandreyer** [comment]
Hi,

hmm, klingt komisch. 

Rufst du immer wieder das put des collector auf? Das darfst du nur einmal(Zeitlich), sonnst mach der das solange bis der Dynamische Speciher alle ist, und dann geht der Rest auch nicht mehr. 

Ich mach das immer mit dem Init Bit, wenn nicht gesetzt, put aufrufen und Init bit setzten, so wird das beim Neustart der SPS immer ordentlich verarbeitet.

Wenn es einen Timeout zum Broker gibt sollte er eigentlich reconnecten.

Ja, das mit dem Collector machts sehr einfach. In der Zigbee2MQTT Bibliothekt hab ich das schön ausgereitzt und macht es am Ende sehr Übersichtlich und schön abgetrennt zu dem MQTT Thema.

Noch mehr Erfolg gehapt?

Grüße Stefan

**Comment by ptC7H12** [comment]
Habe ich eigentlich schon so gemacht.
![Anmerkung 2020-03-29 212708](https://user-images.githubusercontent.com/4460900/77897266-bc101000-7279-11ea-96c8-42cdafcc85a3.jpg)

**Comment by stefandreyer** [comment]
Kannst du das Projekt mal einstellen?

Grüße

**Comment by stefandreyer** [comment]
Noch was erreicht?

**Comment by ptC7H12** [comment]
> Noch was erreicht?

Ne, leider nicht,
[Git.zip](https://github.com/stefandreyer/CODESYS-MQTT/files/4466787/Git.zip)

 habe noch mal die CPU neu gestartet, lief aber trotzdem  nicht.

**Comment by stefandreyer** [comment]
Hi,

habe mal geschaut. Habe das Projekt auf die Windows SPS umgestellt und so geändert das das läuft. Wenn der publish FB sendet, kommts auch zurück.

Probleme: Falschen receive FB genommen, da muss ich meine Bibliothek aufräumen und dokumentieren.

Bei dem neuen receive FB den compare String gesetzt.
SET_MQTT_IN_OUT wieder ein kommentiert.

Wichtige Frage zu deinem Verbindungsproblem: welchen Broker nutzt du? Es gibt Broker die sich nicht an den Standart halten, und ein Problem damit haben, das eine Paket ID sofort wieder verwendet wird, so wie ich das implementiert habe. Wenn Paket für ID 1 durhc ist, wird die wiederverwendet. Problem kenne ich vom IoBroker MQTT Broker. Diese Broker beenden dan die Verbindung.

Ich habe es mit test.mosquitto.org versucht, läuft.


[Git.zip](https://github.com/stefandreyer/CODESYS-MQTT/files/4467091/Git.zip)

Viel Erfolg!
Grüße

**Comment by stefandreyer** [comment]
Läuft?

**Comment by ptC7H12** [comment]
Sorry, komme im Moment nicht dazu das zu testen, melde mich, sobald ich das getan habe...
