### ISSUE TITLE
Raspberry - Exception 

### ISSUE THREAD

**Issue by Louro** [stefandreyer/CODESYS-MQTT#39]
Hey

I'm getting an exception when running the lib in the raspberry, it works fine for the PC.

![image](https://user-images.githubusercontent.com/1134267/79639184-60ef8000-818a-11ea-8747-020785f0d95a.png)

Any idea?

**Comment by stefandreyer** [comment]
Hi,

can you show me the exeption?


The lib runs fine on my raspi.

BR Stefan

**Comment by Louro** [comment]
Hi

Here you go. Maybe this is something related with my own implementation? Strange that just by changing from Win to Rasp it gives that exception.

![image](https://user-images.githubusercontent.com/1134267/79684547-9cde2000-8232-11ea-96ec-7caf590a1868.png)

Regards,
Paulo

**Comment by stefandreyer** [comment]
Hi,

really strange. Does this happen with my example projekt? 

Then I need to set up a test raspi.

BR Stefan
