### ISSUE TITLE
Library download problem

### ISSUE THREAD

**Issue by kurta241** [stefandreyer/CODESYS-MQTT#4]
Hello Stefan,

Downloading the following missing Libraries doesn't work:
Library: OSCAT NETWORK, 1.30 (OSCAT)
Status:  Download fehlgeschlagen
URL:  https://store.codesys.com/CODESYSLibs/OSCAT/OSCATNETWORK/1.30

Library: Common Helper for developement, 1.0.0.0 (Stefan Dreyer)
Status:  Download fehlgeschlagen
URL:   https://store.codesys.com/CODESYSLibs/Stefan Dreyer/CommonHelperfordevelopment/1.0.0.0

Only Version 1.2.1.1 of the OSCAT NETWORK Library is available in the CODESYS Store.
Can you provide us the missing packages/libs? 

Thank you for developing this MQTT Lib.
Kurt

**Comment by stefandreyer** [comment]
Hi,

take a look to

https://github.com/stefandreyer

BR Stefan

**Comment by kurta241** [comment]
Hello,

A good location for the libraries - thanks! Now the project builds without errors.

Best regards
Kurt
