### ISSUE TITLE
Alarm Manager and Trend Storage Compile Errors when using MQTT

### ISSUE THREAD

**Issue by Araforn** [stefandreyer/CODESYS-MQTT#40]
Hello Stefan,

I am raising this issue as im am trying to implement the library as a follow on from issue 33.
https://github.com/stefandreyer/CODESYS-MQTT/issues/33

I successfully connected a test project and get feedback from my devices.
see below image with realtime status of some my devices.

![image](https://user-images.githubusercontent.com/16431270/80094918-ff9b2880-855e-11ea-8257-a9bb36bcdec6.png)

However using this same

 project and adding an alarm manager and a trend manager I get the below compile errors.

![image](https://user-images.githubusercontent.com/16431270/80095059-396c2f00-855f-11ea-96cb-a42d338a3ed7.png)

I have tried everything I can to resolve (changing library version, changing codesys version etc) but nothing works. They seem to be storage related errors. I have attached the export of the working test project.

If you open it and add an alarm or trend manager and try and compile you will see the errors.

Can you let me know if you are too using an alarm manager or trend manager with any use case of your projects.

Perhaps this is a conflict not yet identified?.

[TEST_MQTT.zip](https://github.com/stefandreyer/CODESYS-MQTT/files/4522240/TEST_MQTT.zip)

**Comment by stefandreyer** [comment]
Hi,

I miss FB_BARDEN_MQTT in your export, I can't compile without errors.

So I can not test..
BR Stefan

**Comment by Araforn** [comment]
Apologies Stefan,

Please find now attached with all POU's.

[TEST_MQTT.zip](https://github.com/stefandreyer/CODESYS-MQTT/files/4525448/TEST_MQTT.zip)

**Comment by stefandreyer** [comment]
Hi,

I don't use any of the alarm or trend manager. Webvisu don't too.

Please try this. I made a new projekt and copyed your content.

BR Stefan
[Unbenannt3.zip](https://github.com/stefandreyer/CODESYS-MQTT/files/4529725/Unbenannt3.zip)

**Comment by Araforn** [comment]
> Hi,
> 
> I don't use any of the alarm or trend manager. Webvisu don't too.
> 
> Please try this. I made a new projekt and copyed your content.
> 
> BR Stefan
> [Unbenannt3.zip](https://github.com/stefandreyer/CODESYS-MQTT/files/4529725/Unbenannt3.zip)

Stefan. 

This worked!. I used this to build and import my project. Its been a few days of work but I have my entire application reworked now using your MQTT library.

Can't thank you enough for your help.

Kind Regards,

Paul.
