### ISSUE TITLE
No definition for 'LREAL_TO_STRF'

### ISSUE THREAD

**Issue by vss97** [stefandreyer/CODESYS-MQTT#46]
Hello Stefan

I get the following error on a Rpi. How can this be resolved?

![image](https://user-images.githubusercontent.com/70799116/92302043-32234c00-ef69-11ea-80c8-af7311004843.png)

![image](https://user-images.githubusercontent.com/70799116/92302051-3d767780-ef69-11ea-8c22-38ab8f0548a4.png)

![image](https://user-images.githubusercontent.com/70799116/92302060-4a936680-ef69-11ea-9524-5b73892b9684.png)

Thank you!

**Comment by stefandreyer** [comment]
Hi,

please try the OSCAT BASIC lib from my repository.

BR Stefan
