### ISSUE TITLE
TLS not working

### ISSUE THREAD

**Issue by SanderNID** [stefandreyer/CODESYS-MQTT#49]
Hi,

I downloaded version 3.5.15 and upgraded it to 3.5.16 and used the project: Interation HowTo.project.
I use the free hivemq open broker for testing purpose (https://www.hivemq.com/public-mqtt-broker/).

First problem:
I tried to connect to "broker.hivemq.com", where TLS is false. This works the 'connected' value becomes true.

Thereafter set the TLS to true and got instant pointer error (in IP_CONTROL [From Common Helper for development]): 
![pointerError](https://user-images.githubusercontent.com/74061419/98380712-34795380-2049-11eb-9949-65636ea0f579.png)

To solve this problem I added the pointer to tls_config, which was previously pointing to 0.
Although the exception is gone, the connection is still being refused.

![pointerAdded](https://user-images.githubusercontent.com/74061419/98381084-ab165100-2049-11eb-8dfe-9e5cfc2e11e3.png)

I added the error history. Hope you know what is going wrong, and which values I have to use for tlsMethod, chiperList and verifymode.
![ErrorHistory](https://user-images.githubusercontent.com/74061419/98381372-14965f80-204a-11eb-8a2d-00ee30f41d8d.png)

**Comment by stefandreyer** [comment]
Hi Sander,

does hivemq provide a tls access to there test broker? You need a different port for use tls. see mosquitto for example:

[https://test.mosquitto.org/](url)

Thats why my tls test project work with test.mosquitto.org.

BR Stefan

**Comment by SanderNID** [comment]
Hi Stefan,

Where am I able to change the port number? I know STD uses 1883 and TLS mostly uses 8883, but I didn't find any variable where I can change the port number.

Furthermore, is it the correct way I did by adding the pointer to my own TLS_CONFIG? 

I tried making connection to "test.mosquitto.org" via STD (works) and via TLS, but that still does not work. (could you make a screenshot with example?)
![testMosquittoTLS](https://user-images.githubusercontent.com/74061419/98520162-f7dc7080-2271-11eb-8341-9891757aea39.png)

**Comment by stefandreyer** [comment]
Hi Sander,

Port is given by the server string:
![image](https://user-images.githubusercontent.com/41088808/98536324-e8682200-2287-11eb-8658-671f93ca5d28.png)

The pointer to your own TLS var by CommonTypesAndFunctions.TLS_CONFIG; is ok.

You may have a lookt into my TestOutOfTheBoxTLS FB in My Lib, there you see the handling.

![image](https://user-images.githubusercontent.com/41088808/98536487-31b87180-2288-11eb-8cbb-3493a9713646.png)

I did a test now and had no luck with port 8883 on hivemq.

Good luck.

BR Stefan

**Comment by SanderNID** [comment]
Thanks a lot!
