### ISSUE TITLE
Access violation on reset 

### ISSUE THREAD

**Issue by stefandreyer** [stefandreyer/CODESYS-MQTT#52]
This happpends:

![image](https://user-images.githubusercontent.com/41088808/107688281-c24b8700-6ca7-11eb-8d9a-88a7b67fca3a.png)

Im working on it...

BR Stefan

**Comment by stefandreyer** [comment]
Hi,

one update, crash only happends if MQTT_IN_OUT and so clientFB resists in a GVL.

Looks like a Runtime problem of CODESYS, more investigation needed.

BR

**Comment by stefandreyer** [comment]
Hi,

did made a ticket at CODESYS, problem raises when __delete is called in FB_Exit and the instance is in a GVL.

BR Stefan

**Comment by stefandreyer** [comment]
Hi,

bug was confirmed by CODESYS. Workaround is available.

I'll see to implement it in the next version, If someone needs it bevor, please raise a hand.

BR Stefan

**Comment by stefanroelofs** [comment]
Hi goodmorning,

We are testing your MQTT library in our PLC software, and the same error message appears when we do a reset. 
You say that you have a workaround available? Could you please share that?

We're on CODESYS version: V3.5 SP16 (actually: Lenze PLC Designer 3.23)

Thanks for this great library!

**Comment by stefandreyer** [comment]
Hi Stefan,

the easyest and preferred way would be to place  the MQTT_IN_OUT outside of a GVL, may in a Programm or FB.

Else you have to move the content of the FB_EXIT methods in a new method like this exiter:

![image](https://user-images.githubusercontent.com/41088808/126337524-885fcaa4-bcc9-405e-b81f-3ffd4f6df3f0.png)

If you have fun with the lib you may leve me a star...

Have fun.

BR Stefan

**Comment by stefanroelofs** [comment]
Thanks for the response. 👍 I will test this tomorrow.
Stefan

**Comment by stefandreyer** [comment]
Hi Stefan

did you have succsess?

BR Stefan

**Comment by stefanroelofs** [comment]
Hi, 

Unfortunately not yet.

I placed the MQTT_IN_OUT in a function_block:
![image](https://user-images.githubusercontent.com/37924749/126760032-5d1a4e04-e508-4bbc-a58a-bc7bbdcbf126.png)

And I also put the attribute in several existing 'destroy' methods:
![image](https://user-images.githubusercontent.com/37924749/126760665-9fffd2f4-b8a2-4067-b25c-76406c57d958.png)

This exception is thrown on a Warm Reset:
![image](https://user-images.githubusercontent.com/37924749/126760882-84d00e36-e114-42d9-a094-654a6aee2bd4.png)

**Comment by stefandreyer** [comment]
Hi,

I use this setup in a PRG, you may try a PRG:
![image](https://user-images.githubusercontent.com/41088808/126897253-ff78cdcb-5ef5-4ca3-886c-4ad615349dcc.png)


BR Stefan

**Comment by stefanroelofs** [comment]
Hi,

I've quickly created a small test project with the setup in a PRG like you say, and I don't have any issues anymore.

![image](https://user-images.githubusercontent.com/37924749/127152234-361bc730-bbcc-4d48-b667-814bb9d4ef87.png)

Both when I run it in simulation, or when I download it into a PLC, I don't see any exceptions anymore. 
Thanks for your assistance!
Stefan
