### ISSUE TITLE
Error in MQTT_CONTROL in library version 1.2.0.4

### ISSUE THREAD

**Issue by robinwidhede** [stefandreyer/CODESYS-MQTT#53]
<img width="1049" alt="error_mqtt_control" src="https://user-images.githubusercontent.com/69241003/111705963-c8ea9280-8841-11eb-9cd7-7e33a4c87fc0.PNG">

**Comment by stefandreyer** [comment]
Hi,

i know this, this is annoying, this is no error in the application. I don't know how to get this solved.... After checking pool objects it's gone, press save button, there it is.

BR Stefan

**Comment by stefandreyer** [comment]
Hi,

Solved in latest version, but I don't know why.... 

BR
