### ISSUE TITLE
Any chance for a port to Phoenix Contact

### ISSUE THREAD

**Issue by Portisch** [stefandreyer/CODESYS-MQTT#6]
Is there a way to convert this project to be able to use in a Phoenix Contact PLC?
Or can you give us the raw ST code of the library?

**Comment by stefandreyer** [comment]
Hi Portisch,

the raw ST code is inside the projekt. You can use 
[https://store.codesys.com/engineering/codesys.html](url) (free, just register)
to have a look.

I can provide an OPENplc xml. Is PC Works able to import this?

BR Stefan

**Comment by stefandreyer** [comment]
Hi Portisch

i published an OPENplc XML. Can you use ist?


BR Stefan

**Comment by Portisch** [comment]
Where I can find the OPENplc XML?
PC Worx look like able to import PLCopen XML files.

**Comment by Portisch** [comment]
PC Worx is able to import PLCopen XML - but it isn't working.
Anyway I found another way to make a bridge between PC Worx and MQTT.
