### ISSUE TITLE
Question about compatibility with SoMachine 4.3

### ISSUE THREAD

**Issue by JavierNR** [stefandreyer/CODESYS-MQTT#9]
Hello,

I want to add your MQTT library to SoMachine 4.3 but thows dependencies errors (missing libraries):
![image](https://user-images.githubusercontent.com/1872120/47998359-514bbb00-e0ff-11e8-813d-56179259fb99.png)

As I have Codesys development too, I've tried to add the libraries from Codesys but I suspect that SoMachine uses an older version of Codesys.
Do you have experience with SoMachine? Will try to make it work, but I have little experience dealing with libraries...

**Comment by stefandreyer** [comment]
Hi Javierete,
the only lib I can tell you is VommonTypsAndFunctions, this is available in my GitHub Account. The other libs, phu, I have no experiences with SoMachine, till now I didn't know that this is Schneider PLC Software. Maybe you are able to set the library Version to the Version offerd you by Schneider. 
Next, are all needey librarys offerd by Schneider?

BR Stefan

**Comment by Albalate** [comment]
hola JavierNR.
lograste hacer funcionar en SoMachine la librería?
